// Code generated by protoc-gen-go.
// source: errors.proto
// DO NOT EDIT!

package users

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ErrorCodes int32

const (
	ErrorCodes_UNKNOWN ErrorCodes = 0
)

var ErrorCodes_name = map[int32]string{
	0: "UNKNOWN",
}
var ErrorCodes_value = map[string]int32{
	"UNKNOWN": 0,
}

func (x ErrorCodes) String() string {
	return proto.EnumName(ErrorCodes_name, int32(x))
}

func init() {
	proto.RegisterEnum("users.ErrorCodes", ErrorCodes_name, ErrorCodes_value)
}
