// Code generated by protoc-gen-go.
// source: picture.proto
// DO NOT EDIT!

package users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Picture struct {
	Id      int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	User    *User  `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Picture string `protobuf:"bytes,3,opt,name=picture" json:"picture,omitempty"`
	Default bool   `protobuf:"varint,4,opt,name=default" json:"default,omitempty"`
	Deleted bool   `protobuf:"varint,5,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}

func (m *Picture) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Picture)(nil), "users.Picture")
}
